got_result(failed)
got_reason(The reason)
